added the menu navigation page
hcilabusf/language_learning_app_hci pull request #7
Opened 2020-02-19 19:30 UTC by VGH1

added the menu navigation

2020-03-03 20:20 UTC, VGH1 commented
@alexziweiwang @jin-sj please review my code, let me know if there's anything I can fix.

2020-03-04 19:30 UTC, jin-sj requested changes

2020-03-04 19:30 UTC, jin-sj commented on generating_pages.py
> +with open("word_list.csv") as csv_file:
make into a function

2020-03-04 19:30 UTC, jin-sj commented on generating_pages.py
> +        PAGE_1 = sample_dict[0]
local variables should be lower case

2020-03-04 19:30 UTC, jin-sj commented on main.py
> +    # send_data('baselinestart')
remove commented code

2020-03-04 19:30 UTC, jin-sj commented on main.py
> +    # if canSendMarker and page == 10:
rm commented code

2020-03-04 19:30 UTC, jin-sj commented on main.py
> +    #     server_socket.send_data(PAGES[page].marker_data)
rm commented code

2020-03-04 19:30 UTC, jin-sj commented on main.py
> +            #         send_data('hardend')
commented code

2020-03-04 19:30 UTC, jin-sj commented on page_list.py
> +for i in PATTERN:
make into a function

2020-03-04 21:27 UTC, merged